source 'https://cdn.cocoapods.org/'

inhibit_all_warnings!

install! 'cocoapods', :disable_input_output_paths => true

target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
end